services:
    odiseo_sylius_referrals_plugin.assigner.affiliate:
        class: Odiseo\SyliusReferralsPlugin\Assigner\AffiliateAssigner
        public: true
        arguments:
            - '@odiseo_sylius_referrals_plugin.repository.affiliate'
