services:
    odiseo_sylius_referrals_plugin.controller.shop.statistics_referrals_program:
        class: Odiseo\SyliusReferralsPlugin\Controller\Shop\StatisticsReferralsProgramAction
        public: true
        arguments:
            - '@sylius.context.customer'
            - '@odiseo_sylius_referrals_plugin.repository.referrals_program'
            - '@odiseo_sylius_referrals_plugin.repository.referrals_program_view'
            - '@twig'

    odiseo_sylius_referrals_plugin.controller.shop.create_from_product_referrals_program:
        class: Odiseo\SyliusReferralsPlugin\Controller\Shop\CreateFromProductReferralsProgramAction
        public: true
        arguments:
            - '@sylius.context.customer'
            - '@sylius.repository.product'
            - '@odiseo_sylius_referrals_plugin.factory.referrals_program'
            - '@odiseo_sylius_referrals_plugin.repository.referrals_program'
            - '@router'
