services:
    odiseo_sylius_referrals_plugin.payout.customer_payment_manager:
        class: Odiseo\SyliusReferralsPlugin\Payout\CustomerPaymentManager
        public: true
        arguments:
            - '@odiseo_sylius_referrals_plugin.repository.customer_payment'
            - '@odiseo_sylius_referrals_plugin.repository.referrals_program'
            - '@odiseo_sylius_referrals_plugin.factory.customer_payment'
            - '@sm.factory'
