services:
    odiseo_sylius_referrals_plugin.reward.reward_manager:
        class: Odiseo\SyliusReferralsPlugin\Reward\RewardManager
        public: true
        arguments:
            - '@sylius.repository.promotion'
            - '@sylius.factory.promotion_coupon'
            - '@sylius.repository.promotion_coupon'
            - '@odiseo_sylius_referrals_plugin.email_manager.reward'
            - '%env(resolve:ODISEO_REFERRALS_PROMOTION_CODE)%'
