sylius_mailer:
    emails:
        promotion_reward:
            subject: odiseo_sylius_referrals_plugin.emails.promotion_reward.subject
            template: "@OdiseoSyliusReferralsPlugin/Shop/Email/promotion_reward.html.twig"
