imports:
    - { resource: services/assigner.yaml }
    - { resource: services/controller.yaml }
    - { resource: services/email.yaml }
    - { resource: services/event_listener.yaml }
    - { resource: services/reward.yaml }
