services:
    odiseo_sylius_referrals_plugin.listener.shop.menu_builder:
        class: Odiseo\SyliusReferralsPlugin\EventListener\AccountMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.shop.account, method: addAccountMenuItems }

    odiseo_sylius_referrals_plugin.listener.set_session_from_referrals_program_link:
        class: Odiseo\SyliusReferralsPlugin\EventListener\SetSessionFromReferralsProgramLink
        arguments:
            - '@security.token_storage'
            - '@odiseo_sylius_referrals_plugin.repository.referrals_program'
            - '@odiseo_sylius_referrals_plugin.repository.referrals_program_view'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: setSession }

    odiseo_sylius_referrals_plugin.payout.customer_payment_manager:
        class: Odiseo\SyliusReferralsPlugin\Payout\CustomerPaymentManager
        public: true
        arguments:
            - '@odiseo_sylius_referrals_plugin.repository.customer_payment'
            - '@odiseo_sylius_referrals_plugin.repository.referrals_program'
            - '@odiseo_sylius_referrals_plugin.factory.customer_payment'
            - '@odiseo_sylius_referrals_plugin.manager.customer_payment'
            - '@sm.factory'
   