# This file is part of the Odiseo Referrals Plugin package, a commercial software.
# Only users who have purchased a valid license and accept to the terms of the License Agreement can install
# and use this program.
# Copyright (c) 2018-2022 - Pablo D'amico

sylius_ui:
    events:
        sylius.shop.product.show.right_sidebar:
            blocks:
                referrals_program:
                    template: '@OdiseoSyliusReferralsPlugin/Shop/ReferralsProgram/create.html.twig'
                    priority: 3
        
        sylius.shop.layout.javascripts:
            blocks:
                scripts:
                    template: '@OdiseoSyliusReferralsPlugin/Shop/ReferralsProgram/Product/Index/_scripts.html.twig'

        odiseo_sylius_referrals_plugin.shop.referrals_program.index.before_content:
            blocks:
                statistics:
                    template: '@OdiseoSyliusReferralsPlugin/Shop/ReferralsProgram/Index/statistics.html.twig'
