sylius_ui:
    events:
        sylius.shop.product.show.right_sidebar:
            blocks:
                referrals_program: '@OdiseoSyliusReferralsPlugin/Shop/Product/Show/_referrals_program.html.twig'

        sylius.shop.layout.javascripts:
            blocks:
                referrals_program_scripts:
                    template: '@OdiseoSyliusReferralsPlugin/Shop/Product/Show/_scripts.html.twig'

        odiseo_sylius_referrals_plugin.shop.account.referrals_program.index.subcontent:
            blocks:
                header:
                    template: "@OdiseoSyliusReferralsPlugin/Shop/Account/ReferralsProgram/Index/_header.html.twig"
                    priority: 20
                after_content_header_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 15
                    context:
                        event: odiseo_sylius_referrals_plugin.shop.account.referrals_program.index.after_content_header
                statistics:
                    template: "@OdiseoSyliusReferralsPlugin/Shop/Account/ReferralsProgram/Index/_statistics.html.twig"
                    priority: 10
                after_grid_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        event: odiseo_sylius_referrals_plugin.shop.account.referrals_program.index.after_grid
