sylius_ui:
    events:
        sylius.shop.product.show.right_sidebar:
            blocks:
                referrals_program: '@OdiseoSyliusReferralsPlugin/Shop/Product/Show/_referrals_program.html.twig'

        sylius.shop.layout.javascripts:
            blocks:
                scripts:
                    template: '@OdiseoSyliusReferralsPlugin/Shop/Account/ReferralsProgram/Product/Index/_scripts.html.twig'

        odiseo_sylius_referrals_plugin.shop.referrals_program.index.before_content:
            blocks:
                statistics:
                    template: '@OdiseoSyliusReferralsPlugin/Shop/Account/ReferralsProgram/Index/statistics.html.twig'
