odiseo_sylius_referrals_plugin_shop_referrals_program_index:
    path: /account/dashboard/referrals-program-stats
    methods: [GET]
    defaults:
        _controller: odiseo_sylius_referrals_plugin.controller.referrals_program:indexAction
        _sylius:
            section: shop
            permission: true
            template: "@OdiseoSyliusReferralsPlugin/Shop/ReferralsProgram/index.html.twig"
            vars:
                header: odiseo_sylius_referrals_plugin.ui.referrals_program_stats
                subheader: odiseo_sylius_referrals_plugin.ui.manage_referrals_program
