sylius_resource:
    resources:
        odiseo_sylius_referrals_plugin.affiliate:
            driver: doctrine/orm
            classes:
                model: Odiseo\SyliusReferralsPlugin\Entity\Affiliate
                interface: Odiseo\SyliusReferralsPlugin\Entity\AffiliateInterface
                form: Sylius\Bundle\ResourceBundle\Form\Type\DefaultResourceType
                repository: Odiseo\SyliusReferralsPlugin\Repository\AffiliateRepository
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                factory: Sylius\Component\Resource\Factory\Factory
        odiseo_sylius_referrals_plugin.affiliate_view:
            driver: doctrine/orm
            classes:
                model: Odiseo\SyliusReferralsPlugin\Entity\AffiliateView
                interface: Odiseo\SyliusReferralsPlugin\Entity\AffiliateViewInterface
                form: Sylius\Bundle\ResourceBundle\Form\Type\DefaultResourceType
                repository: Odiseo\SyliusReferralsPlugin\Repository\AffiliateViewRepository
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                factory: Sylius\Component\Resource\Factory\Factory
