# This file is part of the Odiseo Referrals Plugin package, a commercial software.
# Only users who have purchased a valid license and accept to the terms of the License Agreement can install
# and use this program.
# Copyright (c) 2018-2022 - Pablo D'amico

sylius_resource:
    resources:
        odiseo_sylius_referrals_plugin.referrals_program:
            driver: doctrine/orm
            classes:
                model: Odiseo\SyliusReferralsPlugin\Entity\ReferralsProgram
                interface: Odiseo\SyliusReferralsPlugin\Entity\ReferralsProgramInterface
                #form: Odiseo\SyliusMarketplacePlugin\Form\Type\Payout\VendorGatewayConfigType
                #repository: Odiseo\SyliusMarketplacePlugin\Repository\VendorGatewayConfigRepository
                controller: Odiseo\SyliusReferralsPlugin\Controller\ReferralsProgramController
                #factory: Sylius\Component\Resource\Factory\Factory
