# This file is part of the Odiseo Referrals Plugin package, a commercial software.
# Only users who have purchased a valid license and accept to the terms of the License Agreement can install
# and use this program.
# Copyright (c) 2018-2022 - Pablo D'amico

sylius_resource:
    resources:
        odiseo_sylius_referrals_plugin.referrals_program:
            driver: doctrine/orm
            classes:
                model: Odiseo\SyliusReferralsPlugin\Entity\ReferralsProgram
                interface: Odiseo\SyliusReferralsPlugin\Entity\ReferralsProgramInterface
                #form: Odiseo\SyliusMarketplacePlugin\Form\Type\Payout\VendorGatewayConfigType
                repository: Odiseo\SyliusReferralsPlugin\Repository\ReferralsProgramRepository
                controller: Odiseo\SyliusReferralsPlugin\Controller\ReferralsProgramController
                #factory: Sylius\Component\Resource\Factory\Factory

        odiseo_sylius_referrals_plugin.referrals_program_view:
            classes:
                model: Odiseo\SyliusReferralsPlugin\Entity\ReferralsProgramView
                interface: Odiseo\SyliusReferralsPlugin\Entity\ReferralsProgramViewInterface
                repository: Odiseo\SyliusReferralsPlugin\Repository\ReferralsProgramViewRepository

        odiseo_sylius_referrals_plugin.customer_payment:
            classes:
                model: Odiseo\SyliusReferralsPlugin\Entity\CustomerPayment
                interface: Odiseo\SyliusReferralsPlugin\Entity\CustomerPaymentInterface
                repository: Odiseo\SyliusReferralsPlugin\Repository\CustomerPaymentRepository
