sylius_resource:
    resources:
        odiseo_sylius_referrals_plugin.referrals_program:
            driver: doctrine/orm
            classes:
                model: Odiseo\SyliusReferralsPlugin\Entity\ReferralsProgram
                interface: Odiseo\SyliusReferralsPlugin\Entity\ReferralsProgramInterface
                repository: Odiseo\SyliusReferralsPlugin\Repository\ReferralsProgramRepository
                controller: Odiseo\SyliusReferralsPlugin\Controller\ReferralsProgramController

        odiseo_sylius_referrals_plugin.referrals_program_view:
            classes:
                model: Odiseo\SyliusReferralsPlugin\Entity\ReferralsProgramView
                interface: Odiseo\SyliusReferralsPlugin\Entity\ReferralsProgramViewInterface
                repository: Odiseo\SyliusReferralsPlugin\Repository\ReferralsProgramViewRepository

        odiseo_sylius_referrals_plugin.customer_payment:
            classes:
                model: Odiseo\SyliusReferralsPlugin\Entity\CustomerPayment
                interface: Odiseo\SyliusReferralsPlugin\Entity\CustomerPaymentInterface
                repository: Odiseo\SyliusReferralsPlugin\Repository\CustomerPaymentRepository
