winzou_state_machine:
    sylius_order_payment:
        callbacks:
            after:
                odiseo_sylius_referrals_plugin_mark_customer_payments_as_new:
                    on: ["pay"]
                    do: ["@odiseo_sylius_referrals_plugin.payout.customer_payment_manager", "markPaymentsAsNew"]
                    args: ["object"]
