winzou_state_machine:
    sylius_order:
        callbacks:
            after:
                odiseo_sylius_referrals_plugin_create_payments_on_customer:
                    on: ["create"]
                    do: ["@odiseo_sylius_referrals_plugin.payout.customer_payment_manager", "createPayments"]
                    args: ["object"]
