odiseo_sylius_referrals_plugin_shop_partial_referrals_program_create_from_product:
    path: /create-from-product
    methods: [POST]
    defaults:
        _controller: odiseo_sylius_referrals_plugin.controller.referrals_program:createFromProduct

