odiseo_sylius_referrals_plugin_shop_partial_referrals_program_statistics:
    path: /statistics
    methods: [GET]
    defaults:
        _controller: odiseo_sylius_referrals_plugin.controller.shop.statistics_referrals_program

odiseo_sylius_referrals_plugin_shop_partial_referrals_program_create_from_product:
    path: /create-from-product/{id}
    methods: [POST]
    defaults:
        _controller: odiseo_sylius_referrals_plugin.controller.shop.create_from_product_referrals_program

